<?xml version="1.0" encoding="ISO-8859-1"?>
<jsmoothproject>
<JVMSearchPath>registry</JVMSearchPath>
<JVMSearchPath>javahome</JVMSearchPath>
<JVMSearchPath>jrepath</JVMSearchPath>
<JVMSearchPath>jdkpath</JVMSearchPath>
<JVMSearchPath>exepath</JVMSearchPath>
<JVMSearchPath>jview</JVMSearchPath>
<arguments></arguments>
<currentDirectory>${EXECUTABLEPATH}</currentDirectory>
<embeddedJar>true</embeddedJar>
<executableName>EriksCollection.exe</executableName>
<initialMemoryHeap>67108864</initialMemoryHeap>
<jarLocation>..\..\Desktop\EriksCollection.jar</jarLocation>
<mainClassName>Main.java</mainClassName>
<maximumMemoryHeap>134217728</maximumMemoryHeap>
<maximumVersion>1.6.9</maximumVersion>
<minimumVersion>1.2.2</minimumVersion>
<skeletonName>WinService Wrapper</skeletonName>
<skeletonProperties>
<key>ServiceName</key>
<value>WindowsWrapper</value>
</skeletonProperties>
<skeletonProperties>
<key>ServiceDisplayName</key>
<value>WindowsWrapper</value>
</skeletonProperties>
<skeletonProperties>
<key>Message</key>
<value>This program needs Java to run. Please download it at http://www.java.comf</value>
</skeletonProperties>
<skeletonProperties>
<key>Autostart</key>
<value>1</value>
</skeletonProperties>
<skeletonProperties>
<key>Logfile</key>
<value>service.log</value>
</skeletonProperties>
<skeletonProperties>
<key>Interactive</key>
<value>0</value>
</skeletonProperties>
<skeletonProperties>
<key>JniSmooth</key>
<value>0</value>
</skeletonProperties>
<skeletonProperties>
<key>Debug</key>
<value>0</value>
</skeletonProperties>
</jsmoothproject>
